esphome:
  name: jc3248w535-panel_01
  friendly_name: jc3248w535-panel_01

packages:
  base: !include common/base.yaml
  net: !include common/network.yaml
  hw: !include common/hw_display_touch.yaml
  ui: !include variants/ui_josi.yaml

